---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cluster-user
  namespace: local
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cluster-user
  template:
    metadata:
      labels:
        app: cluster-user
    spec:
      containers:
      - name: cluster-user
        image: local/cluster-user:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---
kind: Service
apiVersion: v1
metadata:
  name: cluster-user
  namespace: local
spec:
  type: LoadBalancer
  selector:
    app: cluster-user
  ports:
    - name: http
      port: 8000
      targetPort: 4000
      protocol: TCP
status:
  loadBalancer: {}
---
kind: Service
apiVersion: v1
metadata:
  name: cluster-user
  namespace: local
spec:
  selector:
    app: cluster-user
  ports:
    - name: epmd
      port: 4369
